#pragma once

/* Select hand */
#define MASTER_LEFT
// #define MASTER_RIGHT

/* Mod-Tap */
#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT

/* RGB */
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_DEFAULT_SAT 255
// #define RGBLIGHT_DEFAULT_HUE 128  // Teal HUE
#define RGBLIGHT_DEFAULT_HUE 85  // Green HUE